# Generated by Django 5.2.6 on 2025-09-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
