# Generated by Django 5.2.6 on 2025-10-03 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0002_alter_receta_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
